Code review
guilenzolari/Crypto-API pull request #3
Opened 2024-07-31 16:28 UTC by guilenzolari

![Sem título](https://github.com/user-attachments/assets/be8085bd-807f-4aac-8692-d33ed3bcfdaa)

2024-08-09 18:21 UTC, yagoal requested changes

2024-08-09 18:21 UTC, yagoal commented on CryptoAPI/CryptoAPI/CryptoAPIApp.swift
> +    @StateObject var vm = ContentViewModel(apiService: APIService())
Primeira dica não é uma boa prática utilizar siglas assim.

melhor escrever `viewModel` completamente.

2024-08-09 18:21 UTC, yagoal commented on CryptoAPI/CryptoAPI/Models/FetchState.swift
> +}
Foi necessário mesmo um Comparable ?  você precisa comparar se é maior ou menor ? se for apenas igual pode usar só Equatable que é mais simples

outro ponto é que ao invés de `good` acho que o nome `success` fica melhor

2024-08-09 18:21 UTC, yagoal commented on CryptoAPI/CryptoAPI/Models/Node.swift
> +    static func example1() -> Node {
Essa func foi usada mesmo ? ou só ficou perdida.

Se for algum valor default valeria colocar um getDefaultValue no nome ou algo assim, ou se não remover se não tiver sendo utilizada.

2024-08-09 18:21 UTC, yagoal commented on CryptoAPI/CryptoAPI/Models/Node.swift
> +        return Node(publicKey: "03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f",
Esse tipo de formatação não curto muito, mas é mais questão de gosto ou padrão de projeto

```swift
return Node(
    publicKey: "03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f",
    alias: "ACINQ",
    channels: 2594,
    capacity: 55849260438,
    firstSeen: 1522941222,
    updatedAt: 1720700463,
    city: nil,
    country: City(
        de: "Vereinigte Staaten",
        en: "United States",
        es: "Estados Unidos",
        fr: "États Unis",
        ja: "アメリカ",
        ptBR: "EUA",
        ru: "США",
        zhCN: "美国"
    ),
    isoCode: "US",
    subdivision: nil
)
```

2024-08-09 18:21 UTC, yagoal commented on CryptoAPI/CryptoAPI/Services/APIService.swift
> +    }
Aqui o if e else pode confundir um pouco, da pra usar alguns guards.

```swift
public func fetchData(completion: @escaping (Result<[Node], APIError>) -> Void) {

    guard let url = URL(string: url) else {
        completion(.failure(.badURL))
        return
    }

    let task = URLSession.shared.dataTask(with: url) { data, response, error in
        
        if let error = error as? URLError {
            completion(.failure(.urlSession(error)))
            return
        }
        
        guard let response = response as? HTTPURLResponse,
              (200...299).contains(response.statusCode),
              let data = data else {
            if let response = response as? HTTPURLResponse {
                completion(.failure(.badResponse(response.statusCode)))
            } else {
                completion(.failure(.unknown))
            }
            return
        }

        do {
            let result = try JSONDecoder().decode([Node].self, from: data)
            completion(.success(result))
        } catch let decodingError as DecodingError {
            completion(.failure(.decoding(decodingError)))
        }
    }
    
    task.resume()
}

```

Do jeito que tá ele não retorna a func e continua fazendo o restante, por mais que seja if else.

2024-08-09 18:21 UTC, yagoal commented on CryptoAPI/CryptoAPI/Services/APIServiceProtocol.swift
> +}
Como o protocolo é simples poderia ficar junto do Service mesmo

2024-08-09 18:21 UTC, yagoal commented on CryptoAPI/CryptoAPI/ViewModels/ContentViewModel.swift
> +    @Published var state: FetchState = .good
O State eu sugiro puxar pra cá também, e usar 4 status

initial, success, error e loading

Assim separa melhor os estados

2024-08-09 18:21 UTC, yagoal commented on CryptoAPI/CryptoAPI/Views/CustomListSection.swift
> +    @State var fieldInfo: Any?
Porque isso precisa ser um Any ?

2024-08-09 18:21 UTC, yagoal commented on CryptoAPI/CryptoAPI/Views/ListView.swift
> +        return vm.nodes.filter { $0.alias.localizedCaseInsensitiveContains(searchText)}
essa regra deveria vir da viewModel

2024-08-09 18:21 UTC, yagoal commented on CryptoAPI/CryptoAPI/ViewModels/ContentViewModel.swift
> +    }
Da pra colocar um guard no self só pra tirar os selfs  e não precisa usar self no loading de fora

```swift
func fetchNode() {
    state = .isLoading

    apiService.fetchData { [weak self] result in
        guard let self else { return }
        DispatchQueue.main.async {
            switch result{
            case .success(let results):
                nodes = results
                state = .good
                print("fetched nodes: \(results)")
            case .failure(let error):
                state = .error(error.localizedDescription)
            }
        }
    }
}
```

2024-08-09 18:21 UTC, yagoal commented on CryptoAPI/CryptoAPI/Views/DetailView.swift
> +    @State var viewModel = ContentViewModel(apiService: APIService())
Isso aqui deveria ser um StateObject

Use @StateObject quando estiver trabalhando com um ObservableObject (como um ViewModel) que precisa ser observado por mudanças ao longo do ciclo de vida da View. Ele garante que o objeto seja gerenciado corretamente e que a UI seja atualizada automaticamente sempre que o objeto mudar. Se você usasse @State, o ViewModel poderia ser recriado sempre que a View fosse recriada, perdendo seu estado.

Além de eventuais mudanças que a view deveria fazer na sua ViewModel não vão ser refletidas e perdendo também esse estado se necessário.

2024-08-15 13:23 UTC, guilenzolari commented on CryptoAPI/CryptoAPI/Models/Node.swift
> +    static func example1() -> Node {
A função é usada dentro de test_getting_nodes_success

2024-08-15 14:04 UTC, guilenzolari commented on CryptoAPI/CryptoAPI/Views/CustomListSection.swift
> +    @State var fieldInfo: Any?
fieldInfo pode ser String, Int, City? ou String?
a forma como eu encontrei para poder passar qualquer um desses formatos é utilizando Any?

2024-08-15 14:14 UTC, closed without merging